spring.application.name=PROGETTO-SETTIMANA-17
spring.datasource.url=jdbc:postgresql://localhost:5432/socialnetwork2
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=3001
jwt.secret=TL6QdoAv2k6td5E82wQGsoY41c3LQz9Q5NSHt72vEmXsm2oBev